name: Build and Test

on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:

  build_linux:
    runs-on: ubuntu-latest
    steps:
    - name: Install Rust Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: complete
    - uses: actions/checkout@v2
    - name: Checkout submodules
      run: git submodule update --init
    - name: Build in Release Mode
      run: cargo build --release
    - name: Run tests
      run: cargo test --verbose
    - name: Print CLI Help Message
      run: cargo run --release -- --help

  build_mac:
    runs-on: macos-latest
    steps:
    - name: Install Rust Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: complete
    - uses: actions/checkout@v2
    - name: Checkout submodules
      run: git submodule update --init
    - name: Build in Release Mode
      run: cargo build --release
    - name: Run tests
      run: cargo test --verbose
    - name: Print CLI Help Message
      run: cargo run --release -- --help

  build_windows:
    runs-on: windows-latest
    steps:
    - name: Install Rust Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: complete
    - uses: actions/checkout@v2
    - name: Checkout submodules
      run: git submodule update --init
    - name: Build in Release Mode
      run: cargo build --release
    - name: Run tests
      run: cargo test --verbose
    - name: Print CLI Help Message
      run: cargo run --release -- --help
